

#[theme]
#primaryColor="#F63366"
#backgroundColor="#293745"
#secondaryBackgroundColor="#F0F2F6"
#textColor="white"
#font="Sans-Serif,monospace"



[theme]
primaryColor="#1cb3e0"
backgroundColor="#222f3b"
secondaryBackgroundColor="#344758"
textColor="#d2d2d6"
#font="sans serif"